import ApplicationLayout from '@/common/components/elements/ApplicationLayout';
import ReactQueryProvider from '@/common/components/providers/ReactQueryProvider';
import SessionProvider from '@/common/components/providers/SessionProvider';
import { ThemeProvider } from '@/common/components/providers/ThemeProvider';
import { Toaster } from '@/common/components/ui/sonner';
import { fontInter } from '@/common/libs/Fonts';
import { validateRequest } from '@/common/libs/lucia';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'GeniiEdu',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await validateRequest();

    return (
        <html lang='en' suppressHydrationWarning>
            <body className={fontInter.className}>
                <SessionProvider data={session}>
                    <ReactQueryProvider>
                        <ThemeProvider
                            attribute='class'
                            defaultTheme='system'
                            enableSystem
                            disableTransitionOnChange
                        >
                            <ApplicationLayout>{children}</ApplicationLayout>
                            <Toaster richColors position='top-center' />
                        </ThemeProvider>

                        <ReactQueryDevtools initialIsOpen={false} />
                    </ReactQueryProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
