import { Toaster } from '@/app/_components/ui/sonner';
import { fontInter } from '@/app/_libs/fonts';
import { validateRequest } from '@/app/_libs/lucia';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import NextTopLoader from 'nextjs-toploader';
import type { Metadata } from 'next';
import './globals.css';
import 'react-datetime-picker/dist/DateTimePicker.css';
import 'react-calendar/dist/Calendar.css';
import 'react-clock/dist/Clock.css';
import Providers from '../_providers/providers';

export const metadata: Metadata = {
    title: 'GeniiEdu',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await validateRequest();

    return (
        <html lang='en' suppressHydrationWarning>
            <body className={fontInter.className}>
                <NextTopLoader color='#22c55e' />
                <Providers session={session}>
                    {children}
                    <Toaster richColors position='top-center' />
                    <ReactQueryDevtools initialIsOpen={false} />
                </Providers>
            </body>
        </html>
    );
}
